import type { Metadata } from "next";
import "./globals.css";
import { Container } from "./components/Container/Container";

export const metadata: Metadata = {
  title: "User Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-gray-100">
        <Container>{children}</Container>
      </body>
    </html>
  );
}
